### ISSUE TITLE
Joystick Support Not Working

### ISSUE THREAD

**Issue by AdozenBABYdogs** [SpaxscE/simfphys_base#105]
Everything was working last night with joysticks on a server I was playing on, but this morning, I reconnected and was unable to control anything with joysticks.  I've verified that this isn't a Joystick Controller issue as I can use the wire joystick controllers with my wheel and it still works fine.  Not sure what's going on here.  

Also worth noting, there is no Simfphys entity in the joystick manager menu on singleplayer, but it's present on the server.  Not sure what's going on there

**Comment by SpaxscE** [comment]
you need the joystick module .dll's

**Comment by AdozenBABYdogs** [comment]
I have the .dlls installed in the lua/bin folder

**Comment by AdozenBABYdogs** [comment]
I found it.  In the end, the addon [VJ Base](https://steamcommunity.com/sharedfiles/filedetails/?id=131759821) was causing Joystick to error out.  By removing the mod, the Joystick functionality of simfphys_base started to work again
